### ISSUE TITLE
Icon not displayed when I hosted my flutter website

### ISSUE THREAD

**Issue by yashpaneliya** [tvc12/typicons_flutter#8]
I used icons from this package in my website which I have made using flutter. The icons are displayed on my machine on local server but when I hosted the website then the icons are not visible. It is not showing any error in console also.

I've attached the screenshots here, can you help me out:

On my local server:
![image](https://user-images.githubusercontent.com/58077762/83604514-e8a31980-a593-11ea-8d8b-d4d99f7f3a5a.png)
 
After hosting:
![image](https://user-images.githubusercontent.com/58077762/83604604-10927d00-a594-11ea-887e-684e9161b151.png)

**Comment by tvc12** [comment]
I think a reference to `Typicons` is intentionally omitted because the corresponding font is not included in this source.
You can download typicons font at [here](https://github.com/tvc12/typicons_flutter/blob/master/fonts/typicons.ttf). Then copy it inside your `assets` and update your `FontManifest.json` accordingly

```json
[
  {
    "family": "Typicons",
    "fonts": [
      {
        "asset": "typicons.ttf"
      }
    ]
  }
]
```
See more [here](https://github.com/flutter/flutter_web/tree/master/examples/gallery/web/assets)

**Comment by tvc12** [comment]
close. Because no response a long time
